/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/Results'
import { Route as ProductsPageRouteImport } from './routes/ProductsPage'
import { Route as LocationPageRouteImport } from './routes/LocationPage'
import { Route as DashboardRouteImport } from './routes/Dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ResultsRoute = ResultsRouteImport.update({
  id: '/Results',
  path: '/Results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPageRoute = ProductsPageRouteImport.update({
  id: '/ProductsPage',
  path: '/ProductsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationPageRoute = LocationPageRouteImport.update({
  id: '/LocationPage',
  path: '/LocationPage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/Results': typeof ResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/Results': typeof ResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/Results': typeof ResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Dashboard' | '/LocationPage' | '/ProductsPage' | '/Results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Dashboard' | '/LocationPage' | '/ProductsPage' | '/Results'
  id:
    | '__root__'
    | '/'
    | '/Dashboard'
    | '/LocationPage'
    | '/ProductsPage'
    | '/Results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LocationPageRoute: typeof LocationPageRoute
  ProductsPageRoute: typeof ProductsPageRoute
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Results': {
      id: '/Results'
      path: '/Results'
      fullPath: '/Results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProductsPage': {
      id: '/ProductsPage'
      path: '/ProductsPage'
      fullPath: '/ProductsPage'
      preLoaderRoute: typeof ProductsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LocationPage': {
      id: '/LocationPage'
      path: '/LocationPage'
      fullPath: '/LocationPage'
      preLoaderRoute: typeof LocationPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LocationPageRoute: LocationPageRoute,
  ProductsPageRoute: ProductsPageRoute,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
