/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/Results'
import { Route as DashboardRouteImport } from './routes/Dashboard'
import { Route as ProductsPageRouteImport } from './routes/ProductsPage'
import { Route as ProductDetailPageRouteImport } from './routes/ProductDetailPage'
import { Route as LocationPageRouteImport } from './routes/LocationPage'
import { Route as IndexRouteImport } from './routes/index'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPageRoute = ProductsPageRouteImport.update({
  id: '/ProductsPage',
  path: '/ProductsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDetailPageRoute = ProductDetailPageRouteImport.update({
  id: '/ProductDetailPage',
  path: '/ProductDetailPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationPageRoute = LocationPageRouteImport.update({
  id: '/LocationPage',
  path: '/LocationPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductDetailPage': typeof ProductDetailPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductDetailPage': typeof ProductDetailPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductDetailPage': typeof ProductDetailPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/LocationPage'
    | '/ProductDetailPage'
    | '/ProductsPage'
    | '/dashboard'
    | '/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/LocationPage'
    | '/ProductDetailPage'
    | '/ProductsPage'
    | '/dashboard'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/LocationPage'
    | '/ProductDetailPage'
    | '/ProductsPage'
    | '/dashboard'
    | '/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationPageRoute: typeof LocationPageRoute
  ProductDetailPageRoute: typeof ProductDetailPageRoute
  ProductsPageRoute: typeof ProductsPageRoute
  DashboardRoute: typeof DashboardRoute
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProductsPage': {
      id: '/ProductsPage'
      path: '/ProductsPage'
      fullPath: '/ProductsPage'
      preLoaderRoute: typeof ProductsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProductDetailPage': {
      id: '/ProductDetailPage'
      path: '/ProductDetailPage'
      fullPath: '/ProductDetailPage'
      preLoaderRoute: typeof ProductDetailPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LocationPage': {
      id: '/LocationPage'
      path: '/LocationPage'
      fullPath: '/LocationPage'
      preLoaderRoute: typeof LocationPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationPageRoute: LocationPageRoute,
  ProductDetailPageRoute: ProductDetailPageRoute,
  ProductsPageRoute: ProductsPageRoute,
  DashboardRoute: DashboardRoute,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
