/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProductsPageRouteImport } from './routes/ProductsPage'
import { Route as LocationPageRouteImport } from './routes/LocationPage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIdRouteImport } from './routes/business.$id'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPageRoute = ProductsPageRouteImport.update({
  id: '/ProductsPage',
  path: '/ProductsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationPageRoute = LocationPageRouteImport.update({
  id: '/LocationPage',
  path: '/LocationPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/business/$id': typeof BusinessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/business/$id': typeof BusinessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/LocationPage': typeof LocationPageRoute
  '/ProductsPage': typeof ProductsPageRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/business/$id': typeof BusinessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/LocationPage'
    | '/ProductsPage'
    | '/dashboard'
    | '/results'
    | '/business/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/LocationPage'
    | '/ProductsPage'
    | '/dashboard'
    | '/results'
    | '/business/$id'
  id:
    | '__root__'
    | '/'
    | '/LocationPage'
    | '/ProductsPage'
    | '/dashboard'
    | '/results'
    | '/business/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationPageRoute: typeof LocationPageRoute
  ProductsPageRoute: typeof ProductsPageRoute
  DashboardRoute: typeof DashboardRoute
  ResultsRoute: typeof ResultsRoute
  BusinessIdRoute: typeof BusinessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProductsPage': {
      id: '/ProductsPage'
      path: '/ProductsPage'
      fullPath: '/ProductsPage'
      preLoaderRoute: typeof ProductsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LocationPage': {
      id: '/LocationPage'
      path: '/LocationPage'
      fullPath: '/LocationPage'
      preLoaderRoute: typeof LocationPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationPageRoute: LocationPageRoute,
  ProductsPageRoute: ProductsPageRoute,
  DashboardRoute: DashboardRoute,
  ResultsRoute: ResultsRoute,
  BusinessIdRoute: BusinessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
