import type { CommentProps } from "../types/comment";

export const mockReviews: CommentProps[] = [
	{
		id: "1",
		avatar: "https://i.pravatar.cc/150?img=1",
		location: "Costa Rica",
		name: "Juan Pérez",
		joinedDate: "January 2024",
		rating: 5,
		reviewDate: "June 2026",
		title: "Excellent service",
		body: "Excellent service and very friendly staff.",
		helpfulCount: 12,
	},
	{
		id: "2",
		avatar: "https://i.pravatar.cc/150?img=2",
		location: "San José",
		name: "María López",
		joinedDate: "March 2024",
		rating: 4,
		reviewDate: "May 2026",
		title: "Good experience",
		body: "The overall experience was very good.",
		helpfulCount: 8,
	},
	{
		id: "3",
		avatar: "https://i.pravatar.cc/150?img=3",
		location: "Cartago",
		name: "Carlos Rodríguez",
		joinedDate: "February 2024",
		rating: 3,
		reviewDate: "April 2026",
		title: "Decent place",
		body: "It was okay, nothing too special but worth a visit.",
		helpfulCount: 3,
	},
	{
		id: "4",
		avatar: "https://i.pravatar.cc/150?img=4",
		location: "Heredia",
		name: "Laura Jiménez",
		joinedDate: "June 2023",
		rating: 5,
		reviewDate: "March 2026",
		title: "Absolutely loved it",
		body: "One of the best places I have visited in Costa Rica. Highly recommend.",
		helpfulCount: 20,
	},
	{
		id: "5",
		avatar: "https://i.pravatar.cc/150?img=5",
		location: "Alajuela",
		name: "Diego Mora",
		joinedDate: "September 2023",
		rating: 2,
		reviewDate: "February 2026",
		title: "Not what I expected",
		body: "The place looked better in photos. Service was slow and food was cold.",
		helpfulCount: 5,
	},
	{
		id: "6",
		avatar: "https://i.pravatar.cc/150?img=6",
		location: "Liberia",
		name: "Sofía Vargas",
		joinedDate: "November 2023",
		rating: 4,
		reviewDate: "January 2026",
		title: "Great atmosphere",
		body: "Really loved the vibe of the place. Staff was attentive and kind.",
		helpfulCount: 11,
	},
	{
		id: "7",
		avatar: "https://i.pravatar.cc/150?img=7",
		location: "Limón",
		name: "Andrés Castro",
		joinedDate: "April 2024",
		rating: 5,
		reviewDate: "December 2025",
		title: "Perfect trip",
		body: "Everything was perfect from start to finish. Will definitely come back.",
		helpfulCount: 17,
	},
	{
		id: "8",
		avatar: "https://i.pravatar.cc/150?img=8",
		location: "Puntarenas",
		name: "Valentina Quesada",
		joinedDate: "July 2023",
		rating: 3,
		reviewDate: "November 2025",
		title: "Average visit",
		body: "Nothing stood out but it was a pleasant enough experience overall.",
		helpfulCount: 2,
	},
	{
		id: "9",
		avatar: "https://i.pravatar.cc/150?img=9",
		location: "Nicoya",
		name: "Felipe Solano",
		joinedDate: "January 2023",
		rating: 4,
		reviewDate: "October 2025",
		title: "Really enjoyed it",
		body: "Great food and beautiful surroundings. A little pricey but worth it.",
		helpfulCount: 9,
	},
	{
		id: "10",
		avatar: "https://i.pravatar.cc/150?img=10",
		location: "San Carlos",
		name: "Gabriela Núñez",
		joinedDate: "May 2024",
		rating: 5,
		reviewDate: "September 2025",
		title: "Hidden gem",
		body: "Not many people know about this place but it is truly special. Go before it gets crowded.",
		helpfulCount: 24,
	},
];
